### PR TITLE
Fixed typo, that made the blocking socket mode unconfigurable

### PR DESCRIPTION
**Pull request by alysdal**
Related: https://github.com/php-mqtt/client/issues/133

### CODE REVIEW

**Comment by Namoshek** [comment]
Mh, the fix is not as simple as it seems. The tests I've added are obviously false-positives, but now with the fix they actually show that blocking sockets do not work as expected. I'll need to look into this in more detail...

**Comment by alysdal** [comment]
I was able to solve my issue by creating 2 clients:
1)  One client using blocking socket for publishing the large message and,
2)  One client using non blocking socket for subscribing to updates for the device. 


I did not manage to get the blocking socket client to loop. But as I understood the settings comment it would not work anyway:
```php
    /**
     * Whether to use a blocking socket or not. By default, the socket is non-blocking,
     * which is required when using subscriptions and/or {@see MqttClient::loop()}.
     * In rare cases, it might be required to use a blocking socket though. One such example
     * is when sending large messages (e.g. binaries) and the broker has a limited receive buffer.
     *
     * Note: When using a blocking socket, the MQTT client can get stuck if the socket is broken
     *       or when the broker does not consume the sent data fast enough. Use with caution.
     *
     * @param bool $useBlockingSocket
     * @return ConnectionSettings
     */
    public function useBlockingSocket(bool $useBlockingSocket): ConnectionSettings
```

**Comment by Namoshek** [comment]
Yes, you understood the description correctly. It is not a good idea to use blocking sockets in combination with subscriptions because it will make the client wait for data on the socket during each loop, which can cause timeouts if the broker does not send data frequently.

Using a blocking socket globally (and running the test suite successfully) seems impossible, but I'm thinking about temporarily setting a socket to blocking mode in `writeToSocket($data, $length)` if requested in the connection settings. I'm just not sure how good and fast changing the blocking mode really is, I couldn't find a good answer to that question.

**Comment by Namoshek** [comment]
@alysdal Can you please have a look at #141 and give me feedback whether that fix works for you?

**Comment by alysdal** [comment]
I will check tomorrow. Thanks for already providing a fix :-)

**Pull request closed without merging**
